name: BNN14C
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - numpy=1.23.2
  - matplotlib=
  - pandas=
  - gdown=
  - scikit-learn=
  - tensorflow=
  - tensorflow-probability=
