site_name: Bayesian Neural Network For Radiocarbon Calibration
site_description: "Documentation for the `bnn_for_14C_calibration` Python library"
site_author: "Destin ASHUZA CIRUMANGA"
site_url: https://dest-ash.github.io/bnn_for_14C_calibration/

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            show_root_heading: false

nav:
  - Installation and quick start: index.md
  - Description of lib functions:
      - Calibration functions: reference/calibration.md
      - Plotting functions: reference/calib_plot_functions.md
      - Local cache management functions: reference/manage_cache.md
      - Other (internal) functions:
        - General lib utilities functions: reference/utils.md
        - Bayesian modeling functions:
          - Utilities functions: reference/bnn_models_built_in_utils
          - Built in models: reference/bnn_models_built_in
          - Utilities functions for calibration: reference/calibration_utils
