site_name: Bayesian Neural Network For Radiocarbon Calibration
site_description: "Documentation for the `bnn_for_14C_calibration` Python library"
site_author: "Destin ASHUZA CIRUMANGA"
site_url: https://dest-ash.github.io/bnn_for_14C_calibration/

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            paths: ["src"]
            show_root_heading: false
            show_root_toc_entry: false
            docstring_style: numpy
            show_signature: true
            separate_signature: true
            merge_init_into_class: true

nav:
  - Installation and quick start: index.md
  - User Guide:
      - Calibration functions: reference/calibration.md
      - Plotting functions: reference/calib_plot_functions.md
      - Local cache management functions: reference/manage_cache.md
  - Internals:
    - General lib utilities functions: reference/utils.md
    - Bayesian modeling functions:
      - Utilities functions: reference/bnn_models_built_in_utils.md
      - Built in models: reference/bnn_models_built_in.md
      - Utilities functions for calibration: reference/calibration_utils.md


# gestion équations math
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# reload automatique à chaque modification des docstrings dans les fichiers .py
# ou des pages markdowns (modification des fichiers .md)
watch:
  - src
  - docs